# Generated by Django 4.2.25 on 2025-10-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0107_migrate_filters_to_rich_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamification_rank',
            field=models.CharField(default='Initiate', help_text='Current Warhammer 40k themed rank', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='gamification_score',
            field=models.IntegerField(default=0, help_text='Total points earned from completed tasks'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_rank_upgrade',
            field=models.DateTimeField(blank=True, help_text='When the user last upgraded their rank', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tasks_completed',
            field=models.IntegerField(default=0, help_text='Total number of tasks completed'),
        ),
    ]
